services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.3-alpine3.20"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  socket-server:
    container_name: "socket-server"
    build: ../socket-server
    ports:
      - "4000:4000"

volumes:
  postgres_data:
