name: Automated Testes

on: pull_request

jobs:
  vitest:
    name: Vitest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekcout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"

      - run: npm ci

      - run: npm test
